exclude: 'test'
repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies: [
            flake8,
            flake8-docstrings,
            flake8-mutable,
            flake8-annotations,
          # Does not work with python 3.9
          #flake8-annotations-complexity,
            flake8-bandit,
            flake8-bugbear,
            flake8-comprehensions,
            flake8-variables-names,
            flake8_builtins,
            mccabe,
            naming,
            pycodestyle,
            pyflakes,
            radon
        ]
        verbose: true

  - repo: https://github.com/gvanderest/pylama-pre-commit
    rev: 0.1.2
    hooks:
      - id: pylama
        additional_dependencies: [
            pylint,
            pydocstyle,
            mypy
        ]
        verbose: true

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.0
    hooks:
      - id: commitlint
        stages: [ commit-msg ]
        additional_dependencies: [ '@commitlint/config-angular' ]
